### ISSUE TITLE
Error when listing installed documentation

### ISSUE THREAD

**Issue by heatwole** [kevinaloys/airpy#8]
```python
$ airpy list
Python Project                              Summary
--------------                     ------------------------

Traceback (most recent call last):
  File "/usr/local/bin/airpy", line 9, in <module>
    load_entry_point('airpy==0.0.6', 'console_scripts', 'airpy')()
  File "/usr/local/lib/python2.7/site-packages/airpy/main.py", line 42, in main
    airpy()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/airpy/main.py", line 36, in list
    print_list()
  File "/usr/local/lib/python2.7/site-packages/airpy/list.py", line 26, in print_list
    print(Fore.GREEN + Style.BRIGHT + dir + ' '*(35 - len(dir)) + Fore.WHITE + Style.NORMAL + utils.package_info(dir,'summary'))
  File "/usr/local/lib/python2.7/site-packages/airpy/utils.py", line 18, in package_info
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by kevinaloys** [comment]
Thanks @heatwole for bringing this to the Project AirPy's notice. This is cause of Python 2 not having an equivalent FileNotFounderror exception as available for Python 3. Will be resolved in the next update.

**Comment by kevinaloys** [comment]
This has been fixed.
